<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZIICiat\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZIICiat/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZIICiat.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZIICiat\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZIICiat\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZIICiat',
    'container.build_id' => '2f7b74fe',
    'container.build_time' => 1652132664,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZIICiat');
